# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='bmark.Tag'),
        ),
    ]
